### ISSUE TITLE
Read config file for auto-promote rules

### ISSUE THREAD

**Issue by JonathanCasey** [JonathanCasey/asana_extensions#1]
This will define the config format to setup a rule, along with another that would have the credentials (personal access token for now).

The auto-promote rule would use a `configparser` format, where each rule would have a section such as:
```yaml
[casual rule name]
test report only: <true/false or omit>
user task list: <gid or omit>
workspace: <name or gid>
min time until due: <timedelta format with extensions or omit>
max time until due: <timedelta format with extensions or omit>
src sections include: <names or gids or omit>
src sections exclude: <names or gids or omit>
dst section: <name or gid>
```

For most parameters, the name or gid can be used.  Using the gid is a convenience if the work of finding it has already been done -- it will ensure it continues to match in the future if the name is changed, and it may save some queries.  This will raise an issue if section names are not unique or not found.

The min/max time until due parameters are inclusive, and at least 1 must be used.  The parameters can be listed using the named parameters of `datetime.timedelta`, with an extension added for `months` and `years` parameters.  In order to set a rule to auto-promote items for the next month but exclude the upcoming week, it would be written as `min: 1w1d ; max: 1M`.  TBD if such shorthand abbreviations will be allowed.  To do an exact day such as today, it would be `min: 0d ; max: 0d`.  If `min` omitted, it will presume since the beginning of time and `max` being omitted will be until the end of time.  This does allow catching old tasks by using negative numbers `min: -1d ; max: -1d` "for yesterday" and `max: -2d` for all tasks before yesterday.  It is recommended to run these rules just after midnight (TODO: check how to handle possible timezone issues). 

Rules that overlap are executed in the order they appear in the config file, so that is the user's responsibility to ensure no conflicts.
